### ISSUE TITLE
unstable drawer in navbar

### ISSUE THREAD

**Issue by ad4r5hgs** [100percentBAKA/grocery-management-portal#1]
Drawer pops when the page loads or when the page is refreshed.

**Comment by 100percentBAKA** [comment]
Fixed 
1) useMediaQuery hook from MUI 
2) conditionally rendering the drawer according to screen size 
3) Fixing the drawer state

**Comment by ad4r5hgs** [comment]
<h3>Fixed</h3>

1) useMediaQuery hook from MUI
2) conditionally rendering the drawer according to screen size
3) Fixing the drawer state
